### ISSUE TITLE
Great Start. Few Issues

### ISSUE THREAD

**Issue by TheFinalSword** [setoyuma/CarrotCrusader#1]
Game responds well when I ask it to.

Game is slow, maybe some optimization would fix that up.

I'll need to work on some level geometry.

That's it for now. Good work!

P.S. You coded the background to be Black again. Makes Agravaine's black outline to be transparent.

**Comment by setoyuma** [comment]
Sounds good.
Will work on optimization code for an upcoming patch, animation flexibility for tiles/enemies is up next 
B)
